export { default as livebank } from './images/livebank.png'
export { default as softwaremind } from './images/softwaremind.png'
export { default as ailleron } from './images/ailleron.png'
export { default as slidedown } from './images/slide-down.png'
export { default as phones } from './images/phones.png'

export { default as montserratBold } from './fonts/Montserrat/Montserrat-Bold.ttf'
export { default as montserratRegular } from './fonts/Montserrat/Montserrat-Regular.ttf'
export { default as montserratLight } from './fonts/Montserrat/Montserrat-Light.ttf'
export { default as montserratMedium } from './fonts/Montserrat/Montserrat-Medium.ttf'
